<?php

use App\Models\LpProperty;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\Schema;

class LpPropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // LpProperty::truncate();
        Schema::disableForeignKeyConstraints();
        LpProperty::truncate();
        Schema::enableForeignKeyConstraints();
        // factory(LpProperty::class, 50)->create();
        $scrapingType = array("100", "200", "300");
        $propertyStatus = array("1", "2", "3", "4");
        $propertyConvert = array("0", "100", "200", "300", "999");
        $faker = Faker::create();
        $LpProperty = new LpProperty();
        $LpProperty->insert([
            [
                'id'                             => '1',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $scrapingType[array_rand($scrapingType)],
                'location'                       => '宮城県仙台市青葉区新川',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '渚 里佳',
                'connecting_road'                => '秋田県田中市南区笹田町10-5-1',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '山梨県杉山市南区伊藤町7-2-7',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '2',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100), // "property_no" is abolished!! please refer "*_publish.property_number"
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区折立二丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '田中 浩',
                'connecting_road'                => '秋田県田中市南区笹田町10-5-1',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '静岡県松本市西区廣川町4-9-9',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '3',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区川平五丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '宮沢 直人',
                'connecting_road'                => '滋賀県坂本市北区藤本町6-7-9伊藤ハイツ102号',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '大分県佐々木市西区高橋町7-5-6',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '4',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区愛子東二丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '原田 稔',
                'connecting_road'                => '兵庫県田辺市南区井上町8-2-7',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '岐阜県斉藤市南区高橋町7-4-4中村コーポ110号',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '5',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区川内川前丁',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '鈴木 淳',
                'connecting_road'                => '広島県坂本市北区大垣町5-7-4',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '山梨県中津川市北区藤本町9-4-8',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '6',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区小松島一丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '佐々木 学',
                'connecting_road'                => '埼玉県津田市南区吉本町3-8-7',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '埼玉県井上市南区木村町6-4-6',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '7',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区堤町一丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '佐々木 和也',
                'connecting_road'                => '高知県木村市西区石田町2-3-4中島ハイツ103号',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '千葉県野村市南区吉田町5-9-1',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '8',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区国見ケ丘四丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '杉山 七夏',
                'connecting_road'                => '宮城県近藤市西区野村町5-5-6',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '埼玉県廣川市中央区石田町5-3-7',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '9',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区吉成台一丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '田中 真綾',
                'connecting_road'                => '滋賀県佐藤市東区浜田町10-4-8',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '佐賀県廣川市中央区杉山町5-5-7喜嶋ハイツ109号',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '10',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区台原七丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '若松 洋介',
                'connecting_road'                => '東京都山田市東区小泉町2-6-4野村ハイツ107号',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '沖縄県斉藤市中央区近藤町4-3-2加藤コーポ106号',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '11',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区双葉ケ丘二丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '西之園 明美',
                'connecting_road'                => '山口県中島市西区工藤町2-10-6小林コーポ104号',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '静岡県青山市南区渡辺町10-7-8',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '12',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区南吉成七丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '石田 直子',
                'connecting_road'                => '佐賀県坂本市東区佐藤町6-7-10',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '鳥取県吉田市南区加納町1-1-2中村コーポ104号',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '13',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区千代田町',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '佐藤 陽子',
                'connecting_road'                => '兵庫県中島市西区村山町2-9-10小林コーポ110号',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '三重県山岸市南区青山町3-8-1吉本ハイツ103号',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '14',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区北根二丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '加納 春香',
                'connecting_road'                => '山口県桐山市北区津田町1-8-4加藤ハイツ103号',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '山梨県三宅市北区山口町10-3-10浜田ハイツ105号',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '15',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区北山三丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '江古田 知実',
                'connecting_road'                => '香川県大垣市東区渡辺町9-10-5',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '福島県工藤市北区西之園町3-6-8廣川コーポ108号',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '16',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区作並',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '工藤 拓真',
                'connecting_road'                => '岡山県佐々木市東区高橋町2-4-3西之園ハイツ103号',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '青森県田辺市北区青山町7-10-9近藤ハイツ105号',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '17',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区中江一丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '井上 桃子',
                'connecting_road'                => '岐阜県佐々木市中央区坂本町8-6-5',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '福井県加納市東区佐藤町10-10-5浜田コーポ105号',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '18',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区中山吉成三丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '工藤 知実',
                'connecting_road'                => '三重県高橋市南区佐藤町8-9-1田辺ハイツ110号',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '沖縄県喜嶋市中央区笹田町1-10-5',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '19',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区下愛子',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '近藤 篤司',
                'connecting_road'                => '三重県藤本市南区廣川町6-7-4',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '長崎県木村市中央区田中町2-7-1',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
            [
                'id'                             => '20',
                'lp_scrapings_id'                => rand(1, 3),
                'lp_property_scraping_type_id'   => $scrapingType[array_rand($scrapingType)],
                'lp_property_status_id'          => $propertyStatus[array_rand($propertyStatus)],
                'lp_property_convert_status_id'  => $propertyConvert[array_rand($propertyConvert)],
                'property_no'                    => rand(1, 100),
                // 'scraping_id'                    => rand(1, 3),
                // 'scraping_type_id'               => $faker->randomFloat(6, 0, 5),
                'location'                       => '宮城県仙台市青葉区上杉四丁目',
                'minimum_price'                  => $faker->numberBetween(100, 500),
                'maximum_price'                  => $faker->numberBetween(100, 500),
                'minimum_land_area'              => $faker->randomFloat(6, 0, 5),
                'maximum_land_area'              => $faker->randomFloat(6, 0, 5),
                'building_area'                  => $faker->randomFloat(6, 0, 5),
                'building_age'                   => $faker->numberBetween(100, 500),
                'house_layout'                   => '杉山 太一',
                'connecting_road'                => '福島県山岸市北区笹田町8-3-1',
                'contracted_years'               => Carbon::now(),
                'publish_date'                   => Carbon::now(),
                'traffic'                        => '香川県近藤市南区村山町3-1-5伊藤ハイツ103号',
                'created_at'                     => Carbon::now(),
                'updated_at'                     => Carbon::now(),
            ],
        ]);
    }
}
